### ISSUE TITLE
[Preparation] Milestone을 위한 계획 리스트 작성

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#1]
MIlestone을 위한 계획

댓글로 해야할 일들 뭐가 있을지 적어주시면 되겠습니다.
이를 반영하여 Milestone 작성하겠습니다.
Ex) Team 이름 정하기, 적절한 branch 설정하기(?)

**Comment by zanywhale** [comment]
후반부에 있어야 할 계획들을 적어봤습니다!
[+] Typo Fix, 문법 오류 확인하기
[+] git merge & resolve conflict
[+] 발표 리허설

**Comment by cnj8160** [comment]
발표순서 정하기, 개략적인 시나리오 짜기

**Comment by cnj8160** [comment]
저처럼 git을 이용한 협업 및 버전관리가 익숙치 않은 경우엔 어느정도 연습을 미리 해두어야 할 것 같네요ㅜㅜ

**Comment by 2dvorak** [comment]
pitchme.md 추가

**Comment by 2dvorak** [comment]
typo, 리허설을 위한 오프라인 모임 등은 마일스톤을 따로 만들어서 관리해도 괜찮을 것 같네요.

**Comment by skyshiri** [comment]
발표에 들어갈 내용 대략적으로 맞추기 위한 형식 통일

**Comment by zanywhale** [comment]
모든 리스트 작성이 완료되었기 때문에 해당 이슈를 닫겠습니다.
