### ISSUE TITLE
[Presentation] Team introduction 작성

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#10]
발표에 들어갈 Team introduction 작성이 필요합니다.

**Comment by skyshiri** [comment]
네 알겠습니다.  branch는 issue10-introduction으로 하겠습니다.

**Comment by zanywhale** [comment]
branch 내용 확인했습니다. conclusion도 같이 조금 생각해두시면 좋을 것 같습니다^^

**Comment by zanywhale** [comment]
요청된 PR 받았습니다. 해당 issue는 close하겠습니다.
