### ISSUE TITLE
[Presentation] Presentation 발표 내용 추가하기

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#11]
각자 Presentation에 사용될 발표 내용 추가를 하도록 하겠습니다.
기한은 3월 7일까지 작성해 주시고, 템플릿이 되는 초안은 아래 이슈에 제안된 Format으로 통일하도록 하겠습니다.
부득이한 경우 타협 가능한 선에서 순서, 템플릿 수정이 가능하고 이는 최종 회의때 오프라인 모임에서 이야기를 나눠보도록 하겠습니다.

**Comment by zanywhale** [comment]
Format.md파일이 업데이트 되었습니다. master에 PR되었으니, branch를 생성해서 /members/[EACH_FILE].md 수정해 주시기 바랍니다.
Branch 이름은 issue11-[NickName]으로 통일하겠습니다.

모두 확인해주시고, 본 comment에 이모지 달아주세요^-^

**Comment by zanywhale** [comment]
희의했던 내용 처럼, 각 소개 사이사이에는 적절한 사진을 넣는 것 잊지 말아주세요!
그런 의미에서 images 폴더를 하나 생성하도록 하겠습니다!

**Comment by zanywhale** [comment]
오프라인 미팅에서 리허설이 있는 금요일전에 모든 branch를 통합할 예정입니다.
그리고 추가적으로 CSS적용 및 기타 작업들을 제가 마무리 해야 하기 때문에 
반드시 목요일 오후 6시 까지는 모든 작업을 완료해 주시기 바랍니다!

개인 Presentation은 발표 3분 정도 할 수 있는 분량으로 "완성"해 주시기 바랍니다!
금요일에는 완성된 Presentation을 가지고 리허설 및 팀원끼리의 수정을 할 예정입니다.

**Comment by zanywhale** [comment]
issue11-zanywhale 완료했습니다. Issue #16 으로 PR 요청했습니다.

**Comment by 2dvorak** [comment]
Completed issue11-2dvorak. PR #19 
My hangul isn't working :sob:

**Comment by zanywhale** [comment]
발표내용모두 마무리지어졌습니다.
세세한 수정작업을 모두 마치면 해당 Issue를 닫도록 하겠습니다.
