### ISSUE TITLE
[Work] README.md 작성하기

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#12]
README.md는 채점 기준에 포함되는 내용으로, 여러 필수적인 정보들을 내포하고 있어야 합니다.
필수적인 내용들과 README.md에 있으면 좋을 내용들을 추가하여 보기 좋고 간결하게 정리해 주시면 됩니다.

**Comment by zanywhale** [comment]
https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0228.md
의 채점 기준표를 확인하고 작성해 주시면 좋을 것 같습니다.
특히 gitpitch사용법에 대한 Usage를 추가해주시면 좋을 것 같네요.

**Comment by cnj8160** [comment]
넵 알겠습니다!

**Comment by zanywhale** [comment]
해당 이슈도 branch파서 작성해주시구요
issue12-readme
라는 브랜치로 진행해주세요~~

**Comment by cnj8160** [comment]
README.md에 "How to use GitPitch?" 항목 추가 하였습니다.
오프라인 미팅에서 팀원들과 상의 후(내용을 더 추가할 것인지) README.md 확정 지은 뒤에 풀리퀘스트 요청하겠습니다.

**Comment by zanywhale** [comment]
확인했습니다. 고생하셨습니다^_^

**Comment by cnj8160** [comment]
README.md에 오늘 회의했던 내용들 추가하면 너무 길어질것 같은데 "How to use GitPitch?" 부분을 따로 빼서 md 파일로 작성할까요?

**Comment by 2dvorak** [comment]
gitpitch에 대한 부분 정말 알기 좋게 작성해주셨어요ㅎㅎ 👍 
하지만 README가 길어지면 자칫 conciseness를 해칠 수도 있으니 따로 빼는 것도 좋아보입니다!!

**Comment by zanywhale** [comment]
좋아보입니다ㅎㅎㅎ

**Comment by cnj8160** [comment]
네 그럼 TODO 마일스톤에 "PITCHUSAGE.md 작성하기" 이슈를 추가하고 따로 브렌치를 파서 작업하겠습니다!

**Comment by cnj8160** [comment]
README.md 작성 완료 하였습니다. 
insight 부분을 어떤식으로 작성해야하는지 아직 확신이 안서는데 이부분에 대해 말씀해주시면 반영하겠습니다.

**Comment by zanywhale** [comment]
Presentation 보다는 Usage-gitpitch 라는 제목이 조금 더 어울리지 않을까요?
insight는 branch각각 나눠서 작업했고 네이밍은 어떤 형식으로 한다.
Ex)
- Branch는 Issue에 의해 분리되어 작업
- Branch네이밍은 issue[Number]-[IssueName] 으로 수행

뭐 이런식은 어떨까요?
insight이미지는 정말 이쁜것같아요!

**Comment by cnj8160** [comment]
모두 반영하여 수정 완료 하였습니다.
추가 수정이 필요할 수 있으니 일단은 이대로 두고, 내일 최종 취합 할때 PR 하겠습니다.

**Comment by zanywhale** [comment]
확인했습니다. 오타 및 문법 딱히 틀린거 없어 보이네요 ㅎㅎ
완전히 최종본은 내일 오후 5~6시 이내로 완료해서 `submission` tag 달 예정이니 그때까지는 PR요청 부탁드립니다.

**Comment by 2dvorak** [comment]
merge conflict로 인해 #34 에서 확인중입니다.
