### ISSUE TITLE
[Presentation] Conclusion 추가

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-presentation-team3#23]
Presentation에 Conclusion 추가하기
내용은 오프라인 회의에서 의논한 방향으로 작성.

**Comment by zanywhale** [comment]
너무 Concise하지 않나요 ㅋㅋㅋ
마지막에 저희 모인사진 하나 넣어도 괜찮을 것 같아요.

**Comment by 2dvorak** [comment]
[conclusion slide](https://gitpitch.com/KAIST-IS521/2018s-presentation-team3/issue23-conclusion#/34) 여기서 확인할 수 있습니다

**Comment by 2dvorak** [comment]
오 저번에 사진 찍었던 것 있지않나요?! 😆 
사진 추가는 좋은 것 같고, 슬라이드 제목이나 내용을 더 손봐야 할까요?

**Comment by zanywhale** [comment]
슬라이드 제목을 "Her, 대박" 은 어떠세요?ㅎㅎ 사진은 보내드리겠습니다.
