### ISSUE TITLE
pitchme.md 작성

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-presentation-team3#3]
기본적인 pitchme.md를 작성해 두고 각자 브랜치에서 수정한 다음 pull request 하면 될 것 같습니다.

**Comment by zanywhale** [comment]
먼저 템플릿 작업을 해놓고, 끝난 이후에 개인이 branch따가서 작업하면 될 것 같습니다!

**Comment by 2dvorak** [comment]
Fixed in 9a159c54521a22ee476f87d5d166b19890becb58
Merged in #8

**Comment by zanywhale** [comment]
해당 브랜치가 더 이상 사용 될 필요가 없을 것 같습니다.
Branch 삭제 요청드립니다.
