### ISSUE TITLE
[Work] README merge conflict

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-presentation-team3#34]
#33 에서 conflict가 나서 팀장님 @zanywhale  께서 확인중입니다ㅠ
conflict 난 파일들은 아래의 파일들입니다.
[PITCHME.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/PITCHME.md)
[README.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/README.md)
[images/Lab_view.jpg](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/Lab_view.jpg)
[images/NJ-hate.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/NJ-hate.png)
[images/NJ-love.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/NJ-love.png)
[images/NJ_contest.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/NJ_contest.png)
[images/NJ_name.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/NJ_name.png)
[images/NJ_number.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/NJ_number.png)
[images/lab.jpg](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/lab.jpg)
[images/my_seat.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/my_seat.png)
[images/tmux.jpg](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/tmux.jpg)
[images/whale.png](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/images/whale.png)
[members/donghyeon.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/members/donghyeon.md)
[members/nakjun.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/members/nakjun.md)
[members/sejin.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/members/sejin.md)
[members/seungyeop.md](/KAIST-IS521/2018s-presentation-team3/tree/issue12-readme/members/seungyeop.md)

**Comment by zanywhale** [comment]
해결해서 merge했습니다. ^.^

**Comment by cnj8160** [comment]
감사합니다
수고하셨습니다!!
