### ISSUE TITLE
[TA] Comments on your presentation

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2018s-presentation-team3#37]
Thank you for your efforts in the activity. 
I tracked all your working processes and well listened about your presentation.
There are some feedback collected from all the TAs and professor.

### Presentation Time
```
Except for introduction and conclusion time.
- 오동현: 2분 24초
- 이승엽: 2분 22초
- 최낙준: 2분 55초
- 정세진: 3분 18초
```

### Team Comment
```
- 초반에 티에이에 대해서 말한 점이 좋음.
- 훌륭한 스토리, 흐름, 발표매너 역시 좋았고 몰입도도 있었음.
- 발표가 상당히 매끄러웠고, 자기홍보또한 잘 되었음.
- 발표를 위트 있게 잘 함.
- 채점 기준을 한 번 더 살핀다면 더 높은 점수를 받을 수 있을 것임.
- 전체적인 흐름이 좋았으며, 재밌고 집중이 잘 되는 발표였음.
- 제한 시간 준수, template 등 자잘한 부분에 대해서 좀 더 신경을 쓰면 좋았을 듯.
- 발표의 흐름이 깔끔했음(스토리가 있는 발표!)
- 마지막 단체사진과 함께 간결하면서도, 좋은 마무리를 했음.
- 형식이 통일 되지 않는 부분이 존재.
- 주어진 시간을 초과.
- 재미있는 발표였습니다.
- 세진씨 슬라이드의 통일성 해치는 부분이 아쉽습니다.
- 세진씨만 주어진 시간을 넘겼지만, 팀 발표였기 때문에 다 같이 연습을 더 해서 시간을 맞추었으면 하는 
  아쉬움이 남습니다.
- 전체적으로 발표를 흥미롭게 이끌어 나간 점이 좋았습니다.
- 재미있는 발표였습니다.
```

### Member Comment
* 오동현
  * 그램토시가 뭔지 정확히 모르겠음. 청중이 다 알거라는 가정은 위험함.
  * 그램토시를 사용한다는 점이 흥미롭긴 하지만, 그램토시가 일반적인 용어가 아닌 만큼 windows 보다는 그램토시에 대해서 먼저 설명을 하면 좋았을 것 같음. 추가로, 그램토시가 LG gram + 해킨토시의 합성어라는 것을 그림으로 잘 나타내 주었으면 좋았을 것 같음.
* 이승엽
  * 드보락을 사용해야한다고만 하고, 본인이 사용하는지는 얘기하지 않음. 본인이 드보락을 사용한다면, 그에 관한 에피소드는? 자신을 어필할 수 있는 포인트를 더 이야기 해야함.
  * 무늬만 전자과라고 하면서 사진에는 회로 사진을 넣어두는게 모순되어 보였음. 회로 사진 대신 TEE나 다른 관심 분야의 사진을 넣는게 더 좋았을 듯.
  * 왜 그 닉네임을 사용하는지 catch하기가 어려웠음.
* 최낙준
  * attraction을 주는 좋은 인트로. 이해하기 쉬운 슬라이드. 굳!
  * 재밌는 intro를 포함하여 전체적으로 지루하지 않은 발표였음.
* 정세진
  * 발표를 한다기 보다는 읽는 느낌이 강했음.
  * 스토리 포함된 PR 좋았음.
  * 개발 환경 슬라이드에 있는 사진의 글씨가 너무 작아서 보이지 않음.

That's all comments from TAs and professor.
Again, thank you for your efforts. I hope that you guys could improve your own collaboration and presentation skills through this activity.

Thanks, 
Seongil Wi

**Comment by zanywhale** [comment]
상세하고 좋은 `comment`감사합니다.
이를 참고하여 기회가 된다면 더욱 나은 presentation을 할 수 있을 것 같습니다.
감사합니다. ^_^

**Comment by 2dvorak** [comment]
지난번 피드백도 그렇고, 매번 좋은 피드백을 주셔서 감사합니다.
다음 발표부터 반영해서 더욱 발전하는 모습 보일 수 있도록 할게요.

**Comment by cnj8160** [comment]
코멘트 감사드립니다!
말씀해주신 부분 참고해서 발표기술을  더 발전시키도록 하겠습니다 ~(^ㅇ^~)(~^ㅇ^)~

**Comment by sangkilc** [comment]
@seongil-wi  Thank you for creating the issue. I have a comment about your comment though :) I see some overlapping comments. For example, "재미있는 발표였습니다" appeared twice. I believe this is because two TAs gave the same comment. I hope you can dedup such cases for the next time.
