### ISSUE TITLE
[Presentation] Prepare presentation

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#39]
프리젠테이션을 준비해야합니다.
이번 것은 발표가 아닌, 우리가 PGP를 정말로 잘 사용하고 있다는 것을 보여주면 됩니다.

**Comment by 2dvorak** [comment]
PGP gitpitch 편집은 이전과 비슷하게 브랜치를 만들어서 하되, pgp-issue39-skyshiri 이런식으로 진행하겠습니다.

**Comment by 2dvorak** [comment]
굳이 새로운 브랜치를 파지 않고 pgp 브랜치에 작업하겠습니다. 단, 커밋 시 서명과 이슈 넘버링 잊지 말아주시와요. 🙏

**Comment by cnj8160** [comment]
gitpitch의 대략적인 순서는 이러면 어떨까요?
1. key 만드는 과정(명령어 등)
2. 각 멤버별 공개키(ID) 나열 (이미지 등으로)
3-1. 서명 : 서명 하는 방법 + 각 멤버별 Web of trust 그래프
3-2. 서명 : 개인과제에서 각자 키로 서명해서 commit 한 것 보여주기 or #40 에서 동현님 말씀대로 README.md 하나씩 삭제하고 commit 한것 보여주기
4-1. 암호화 및 복호화 : 파일 암호화 및 복호화 하는 방법 (명령어 등)
4-2. 암호화 및 복호화 : 서로 암호화 메일 주고 받은것 + 카카오톡에서 암호화 메시지 주고받은 것
5. 마무으리!

**Comment by zanywhale** [comment]
gitpitch는 저희가 했던 내용 한번에 정리해서 넣도록 하겠습니다.

**Comment by zanywhale** [comment]
모든 presentation 자료 생성이 완료되었기 때문에 해당 이슈를 닫겠습니다.
