### ISSUE TITLE
[Presentation] 오프라인 모임 및 리허설

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#4]
오프라인 모임 및 리허설 관리

**Comment by cnj8160** [comment]
대부분 작업은 온라인으로 진행할 예정이지만 부득이하게 직접 만나서 진행해야 할때는 여기서 시간 약속 잡으면 될것 같습니다~

**Comment by cnj8160** [comment]
조만간 한번 함께 모여서 작업해야 할 것 같은데 다들 이번주 금요일 괜찮으신가요?

**Comment by zanywhale** [comment]
오늘 오프라인 리허설을 마쳤습니다. 해당 Issue는 close하도록 하겠습니다.
