### ISSUE TITLE
[Using] Just using PGP!

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#40]
PGP를 마음껏 사용하시면 됩니다.
지금부터는 모든 commit에 서명을 해서 올리도록 하겠습니다.
서명 방법은 다음과 같습니다.

```
git config --global user.signingkey <key_id>
git commit -S -m "Signed commit!"
```

이외에도 활발한 PGP사용에 대한 예시를 reply로 남겨주세요!
Ex1) 중요한 내용에 대한 공유를 PGP로 Encrpyt해서 보내기
Ex2) 메일에 PGP를 적용하여 전송하기

**Comment by zanywhale** [comment]
03bc9bb45d098b185cdb7bad72b0094b0d97d872

**Comment by zanywhale** [comment]
1. 일반 string encrypt해서 서로 decrypt해보기
2. mutt 이용해서 메일보내기

**Comment by zanywhale** [comment]
모두들 한 번 이상의 인증된(?) 커밋을 위해 PGP branch에서 README.md의 insight, Directory structure, abstract을 각각 하나씩 제거하고 `commit -S -m ""`으로 `Verfied` commit을 해보도록 할게요!

**Comment by cnj8160** [comment]
제가 abstract 삭제하고 제 키로 서명된 commit 수행하였습니다!

**Comment by skyshiri** [comment]
이승엽님과 서로 pgp로 암호화하여 이메일 주고받았습니다.

**Comment by cnj8160** [comment]
저도 동현님의 공개키로 암호화하여 이메일을 전송하였습니다.

**Comment by 2dvorak** [comment]
insight 삭제하고 서명해서 커밋했습니다!!

**Comment by zanywhale** [comment]
Issue #43 새로운 이슈 추가!

**Comment by zanywhale** [comment]
여러 미션들이 끝났기 때문에 본 이슈를 닫겠습니다.
