### ISSUE TITLE
[Work] README.md 수정

### ISSUE THREAD

**Issue by 2dvorak** [KAIST-IS521/2018s-presentation-team3#41]
전체적인 틀은 유지하고 내용을 고치겠습니다.

**Comment by cnj8160** [comment]
키 생성 및 서명을 위한 명령어 등을 README.md에 추가하면 너무 길어지니 따로 md 파일을 생성하고 README.md에서 링크 걸도록 하겠습니당

**Comment by zanywhale** [comment]
- Table of contents라는 큰 틀은 유지하고, 대신 내용이 좀 바뀌겠네요!
- Usage-gitpitch는 master에 병합할 게 아니기 때문에 맨 뒤에 master->pgp로 변경하면 될 것 같습니다.
- 현재 Abstract가 포함되어 있지 않은데, Abstract에 우리가 얼마나 pgp를 사랑하는지를 Presentation에 표현했다! 뭐 이런내용을 적으면 좋지 않을까요?
- 저희 정리해 놓은 명령어들을 다른 MD파일에 넣어서 링크를 추가합시다!!!
