### ISSUE TITLE
[TA] Comments from the Prof. Cha on your <presentation> activity 3

### ISSUE THREAD

**Issue by seongil-wi** [KAIST-IS521/2018s-presentation-team3#45]
Hi, this is team 3 TA Seongil Wi.
I upload comments from professor about presentation material activity 3.

Team 3

- 재미와 교훈 모두 성공적으로 보여줌.
- 훌륭한 팀웍 역시 돋보였으며, 슬라이드가 전체적으로 읽기에 매우 편함.
- 단 title 슬라이드의 경우 정확히 프레젠테이션에서 내가 뭘 하겠다라는 제목을
  확실히 보여줘야하는데, 단순히 HER이라는 팀명만 나와있음. 예를 들면 IS-521 PGP
  Activity에 대한 발표라는 것을 확실히 제목에서부터 보여줄 필요가 있음.

Thanks.
Seongil wi.

**Comment by zanywhale** [comment]
좋은 리뷰 감사합니다. 앞으로 Presentation 시에 적용하겠습니다!
