### ISSUE TITLE
[Presentation] 발표 내용 Format 작성

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-presentation-team3#7]
발표 내용 Format 통일 및 제작

**Comment by zanywhale** [comment]
발표 내용 Format 작성을 오늘 온라인 회의에서 이야기 한 것을 차용하도록 하겠습니다!
작업이 완료되는 대로 PITCHME.md의 Format을 issue7_format branch로 수정해서 PR요청해주시길 바랍니다.

**Comment by 2dvorak** [comment]
3d52a4ddf21370c30744fa95584f0a5e63503f0d format.md 기본적인 내용 추가하였습니다.
#14 에 pr 하였습니다!

**Comment by zanywhale** [comment]
PR받았습니다. 해당 브랜치 삭제 부탁드립니다. ^_^
